/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movieknight;

/**
 *
 * @author User
 */
public class Action extends javax.swing.JFrame {

    /**
     * Creates new form Action
     */
    public Action() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Skyfall = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        skyfallPoster = new javax.swing.JLabel();
        Avengers = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MissionImpossible = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FF8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        JusticeLeague = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Skyfall.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Year of Release: 2012");
        Skyfall.add(jLabel9);
        jLabel9.setBounds(100, 370, 220, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Director Name: Sam Mendes");
        Skyfall.add(jLabel8);
        jLabel8.setBounds(70, 350, 320, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Movie Name: Skyfall");
        Skyfall.add(jLabel5);
        jLabel5.setBounds(110, 300, 310, 22);

        skyfallPoster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skyfall resize.jpg"))); // NOI18N
        Skyfall.add(skyfallPoster);
        skyfallPoster.setBounds(0, 0, 380, 400);

        getContentPane().add(Skyfall, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 25, 380, 399));

        Avengers.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Year of Release:2012");
        Avengers.add(jLabel13);
        jLabel13.setBounds(110, 50, 210, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Director: Joss Whedon");
        Avengers.add(jLabel2);
        jLabel2.setBounds(110, 30, 240, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avengers resize.jpg"))); // NOI18N
        Avengers.add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 360);

        getContentPane().add(Avengers, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, 400, 360));

        MissionImpossible.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Year of Release:1996");
        MissionImpossible.add(jLabel7);
        jLabel7.setBounds(80, 300, 250, 22);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Director Name: Brian De Palm");
        MissionImpossible.add(jLabel6);
        jLabel6.setBounds(80, 270, 290, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Movie Name: Mission Impossible");
        MissionImpossible.add(jLabel4);
        jLabel4.setBounds(80, 250, 293, 20);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Movie\\Action\\mission impossible resize 2.jpg")); // NOI18N
        MissionImpossible.add(jLabel3);
        jLabel3.setBounds(0, 0, 400, 392);

        getContentPane().add(MissionImpossible, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 400, 390));

        FF8.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Year of Release:2017");
        FF8.add(jLabel12);
        jLabel12.setBounds(90, 220, 230, 22);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Director: F. Gary Gray");
        FF8.add(jLabel11);
        jLabel11.setBounds(90, 200, 220, 20);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Movie\\Action\\fate of the furious resize.jpg")); // NOI18N
        FF8.add(jLabel10);
        jLabel10.setBounds(0, 0, 400, 385);

        getContentPane().add(FF8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 400, 360));

        JusticeLeague.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Year of Release:2017");
        JusticeLeague.add(jLabel16);
        jLabel16.setBounds(130, 360, 200, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Director:Zack Snyder");
        JusticeLeague.add(jLabel15);
        jLabel15.setBounds(130, 330, 210, 22);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/justice league resize.jpg"))); // NOI18N
        JusticeLeague.add(jLabel14);
        jLabel14.setBounds(15, 28, 414, 400);

        getContentPane().add(JusticeLeague, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 60, 430, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Action.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Action.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Action.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Action.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Action().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Avengers;
    private javax.swing.JPanel FF8;
    private javax.swing.JPanel JusticeLeague;
    private javax.swing.JPanel MissionImpossible;
    private javax.swing.JPanel Skyfall;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel skyfallPoster;
    // End of variables declaration//GEN-END:variables
}
