/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package movieknight;

/**
 *
 * @author User
 */
public class LogInPage extends javax.swing.JFrame {
    //private int flag;

    /** Creates new form LogInPage */
    public LogInPage() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        doneButton = new javax.swing.JButton();
        userIdLabelLogIn = new javax.swing.JLabel();
        passwordLableLogIn = new javax.swing.JLabel();
        Backbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        getContentPane().setLayout(null);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(120, 50, 141, 30);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(120, 100, 141, 30);

        doneButton.setBackground(new java.awt.Color(0, 51, 102));
        doneButton.setForeground(new java.awt.Color(255, 255, 255));
        doneButton.setText("Login");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });
        getContentPane().add(doneButton);
        doneButton.setBounds(30, 170, 70, 30);

        userIdLabelLogIn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userIdLabelLogIn.setForeground(new java.awt.Color(255, 255, 255));
        userIdLabelLogIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userIdLabelLogIn.setText("User ID");
        userIdLabelLogIn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(userIdLabelLogIn);
        userIdLabelLogIn.setBounds(20, 50, 82, 34);

        passwordLableLogIn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        passwordLableLogIn.setForeground(new java.awt.Color(255, 255, 255));
        passwordLableLogIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordLableLogIn.setText("Password");
        getContentPane().add(passwordLableLogIn);
        passwordLableLogIn.setBounds(20, 100, 82, 29);

        Backbutton.setBackground(new java.awt.Color(0, 0, 0));
        Backbutton.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        Backbutton.setForeground(new java.awt.Color(255, 255, 255));
        Backbutton.setText("Back");
        Backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Backbutton);
        Backbutton.setBounds(200, 290, 100, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\2.1\\MovieKnight\\MovieKnight\\src\\movieknight\\secure.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 310, 330);

        getAccessibleContext().setAccessibleParent(this);

        setSize(new java.awt.Dimension(333, 385));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        // TODO add your handling code here:
        new TwoChoices().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_doneButtonActionPerformed

    private void BackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbuttonActionPerformed
        // TODO add your handling code here:
        new Welcome().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbutton;
    private javax.swing.JButton doneButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel passwordLableLogIn;
    private javax.swing.JLabel userIdLabelLogIn;
    // End of variables declaration//GEN-END:variables

}
