/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movieknight;

/**
 *
 * @author HP PAVILION
 */
public class MovieSuggetions extends javax.swing.JFrame {

    /**
     * Creates new form MovieSuggetions
     */
    
    public MovieSuggetions() {
        initComponents();
        genrepanel.setVisible(true);
        actionPanel.setVisible(false);
        romancePanel.setVisible(false);
        fantasyPanel.setVisible(false);
        dramaPanel.setVisible(false);
        comedyPanel.setVisible(false);
        horrorPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genreButton = new javax.swing.ButtonGroup();
        actionSubButtonGroup = new javax.swing.ButtonGroup();
        romanceSubButtonGroup = new javax.swing.ButtonGroup();
        fantasySubButtonGroup = new javax.swing.ButtonGroup();
        dramaSubButtonGroup = new javax.swing.ButtonGroup();
        comedySubButtonGroup = new javax.swing.ButtonGroup();
        horrorSubButtonGroup = new javax.swing.ButtonGroup();
        genrepanel = new javax.swing.JPanel();
        actionRadioButton = new javax.swing.JRadioButton();
        genreLabel = new javax.swing.JLabel();
        romanceRadioButton = new javax.swing.JRadioButton();
        fantasyRadioButton = new javax.swing.JRadioButton();
        dramaRadioButton = new javax.swing.JRadioButton();
        comedyRadioButton = new javax.swing.JRadioButton();
        horrorRadioButton = new javax.swing.JRadioButton();
        goTosubGenre = new javax.swing.JButton();
        fantasyPanel = new javax.swing.JPanel();
        fantasyDramaRadioButton = new javax.swing.JRadioButton();
        fantasyAdventureRadioButton = new javax.swing.JRadioButton();
        fantasyActionRadioButton = new javax.swing.JRadioButton();
        dramaPanel = new javax.swing.JPanel();
        dramaCrimeRadioButton = new javax.swing.JRadioButton();
        dramaComedyRadioButton = new javax.swing.JRadioButton();
        dramaThrillerRadioButton = new javax.swing.JRadioButton();
        dramaFictionRadioButton = new javax.swing.JRadioButton();
        comedyPanel = new javax.swing.JPanel();
        comedyComedyDramaRadioButton = new javax.swing.JRadioButton();
        comedyRomanceRadioButton = new javax.swing.JRadioButton();
        comedyDramaRadioButton = new javax.swing.JRadioButton();
        comedyActionRadioButton = new javax.swing.JRadioButton();
        horrorPanel = new javax.swing.JPanel();
        horroThrillerRadioButton = new javax.swing.JRadioButton();
        horrorCrimeRadioButton = new javax.swing.JRadioButton();
        romancePanel = new javax.swing.JPanel();
        romanceDramaRadioButton = new javax.swing.JRadioButton();
        romanceComedyRadioButton = new javax.swing.JRadioButton();
        actionPanel = new javax.swing.JPanel();
        actionThrillerRadioButton = new javax.swing.JRadioButton();
        actionSuperheroRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        genrepanel.setBackground(new java.awt.Color(255, 255, 255));

        genreButton.add(actionRadioButton);
        actionRadioButton.setText("Action");
        actionRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionRadioButtonActionPerformed(evt);
            }
        });

        genreLabel.setBackground(new java.awt.Color(153, 255, 255));
        genreLabel.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        genreLabel.setForeground(new java.awt.Color(0, 51, 153));
        genreLabel.setText("Choose a Genre");

        genreButton.add(romanceRadioButton);
        romanceRadioButton.setText("Romance");
        romanceRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                romanceRadioButtonActionPerformed(evt);
            }
        });

        genreButton.add(fantasyRadioButton);
        fantasyRadioButton.setText("Fantasy");
        fantasyRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fantasyRadioButtonActionPerformed(evt);
            }
        });

        genreButton.add(dramaRadioButton);
        dramaRadioButton.setText("Drama");
        dramaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dramaRadioButtonActionPerformed(evt);
            }
        });

        genreButton.add(comedyRadioButton);
        comedyRadioButton.setText("Comedy");
        comedyRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comedyRadioButtonActionPerformed(evt);
            }
        });

        genreButton.add(horrorRadioButton);
        horrorRadioButton.setText("Horror");
        horrorRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horrorRadioButtonActionPerformed(evt);
            }
        });

        goTosubGenre.setBackground(new java.awt.Color(51, 102, 255));
        goTosubGenre.setForeground(new java.awt.Color(255, 255, 255));
        goTosubGenre.setText("GO");
        goTosubGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goTosubGenreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout genrepanelLayout = new javax.swing.GroupLayout(genrepanel);
        genrepanel.setLayout(genrepanelLayout);
        genrepanelLayout.setHorizontalGroup(
            genrepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genrepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(genrepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genreLabel)
                    .addGroup(genrepanelLayout.createSequentialGroup()
                        .addComponent(actionRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(romanceRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fantasyRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dramaRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comedyRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(genrepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(genrepanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(goTosubGenre))
                    .addGroup(genrepanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(horrorRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        genrepanelLayout.setVerticalGroup(
            genrepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, genrepanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(genrepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genreLabel)
                    .addComponent(goTosubGenre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(genrepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actionRadioButton)
                    .addComponent(romanceRadioButton)
                    .addComponent(fantasyRadioButton)
                    .addComponent(dramaRadioButton)
                    .addComponent(comedyRadioButton)
                    .addComponent(horrorRadioButton))
                .addGap(31, 31, 31))
        );

        getContentPane().add(genrepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 793, -1));

        fantasyPanel.setBackground(new java.awt.Color(153, 153, 255));
        fantasyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fantasySubButtonGroup.add(fantasyDramaRadioButton);
        fantasyDramaRadioButton.setText("Drama");
        fantasyPanel.add(fantasyDramaRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 18, -1, -1));

        fantasyAdventureRadioButton.setText("Adventure");
        fantasyPanel.add(fantasyAdventureRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 59, -1, -1));

        fantasyActionRadioButton.setText("Action");
        fantasyPanel.add(fantasyActionRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 100, -1, -1));

        getContentPane().add(fantasyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 181, 114, 132));

        dramaPanel.setBackground(new java.awt.Color(0, 102, 51));

        dramaSubButtonGroup.add(dramaCrimeRadioButton);
        dramaCrimeRadioButton.setText("Crime");

        dramaSubButtonGroup.add(dramaComedyRadioButton);
        dramaComedyRadioButton.setText("Comedy Drama");
        dramaComedyRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dramaComedyRadioButtonActionPerformed(evt);
            }
        });

        dramaSubButtonGroup.add(dramaThrillerRadioButton);
        dramaThrillerRadioButton.setText("Thriller");

        dramaSubButtonGroup.add(dramaFictionRadioButton);
        dramaFictionRadioButton.setText("Fiction");

        javax.swing.GroupLayout dramaPanelLayout = new javax.swing.GroupLayout(dramaPanel);
        dramaPanel.setLayout(dramaPanelLayout);
        dramaPanelLayout.setHorizontalGroup(
            dramaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dramaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dramaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dramaCrimeRadioButton)
                    .addComponent(dramaComedyRadioButton)
                    .addComponent(dramaThrillerRadioButton)
                    .addComponent(dramaFictionRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dramaPanelLayout.setVerticalGroup(
            dramaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dramaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dramaCrimeRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dramaComedyRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dramaFictionRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dramaThrillerRadioButton)
                .addContainerGap())
        );

        getContentPane().add(dramaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 181, -1, 132));

        comedyPanel.setBackground(new java.awt.Color(255, 255, 102));

        comedySubButtonGroup.add(comedyComedyDramaRadioButton);
        comedyComedyDramaRadioButton.setText("Comedy Drama");

        comedySubButtonGroup.add(comedyRomanceRadioButton);
        comedyRomanceRadioButton.setText("Romance");

        comedySubButtonGroup.add(comedyDramaRadioButton);
        comedyDramaRadioButton.setText("Drama");

        comedySubButtonGroup.add(comedyActionRadioButton);
        comedyActionRadioButton.setText("Action");

        javax.swing.GroupLayout comedyPanelLayout = new javax.swing.GroupLayout(comedyPanel);
        comedyPanel.setLayout(comedyPanelLayout);
        comedyPanelLayout.setHorizontalGroup(
            comedyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comedyPanelLayout.createSequentialGroup()
                .addGroup(comedyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comedyComedyDramaRadioButton)
                    .addComponent(comedyRomanceRadioButton)
                    .addComponent(comedyDramaRadioButton)
                    .addComponent(comedyActionRadioButton))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        comedyPanelLayout.setVerticalGroup(
            comedyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comedyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comedyComedyDramaRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comedyRomanceRadioButton)
                .addGap(18, 18, 18)
                .addComponent(comedyDramaRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comedyActionRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(comedyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 181, -1, 132));

        horrorPanel.setBackground(new java.awt.Color(0, 51, 102));

        horrorSubButtonGroup.add(horroThrillerRadioButton);
        horroThrillerRadioButton.setText("Thriller");

        horrorSubButtonGroup.add(horrorCrimeRadioButton);
        horrorCrimeRadioButton.setText("Crime");

        javax.swing.GroupLayout horrorPanelLayout = new javax.swing.GroupLayout(horrorPanel);
        horrorPanel.setLayout(horrorPanelLayout);
        horrorPanelLayout.setHorizontalGroup(
            horrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(horrorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(horrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(horroThrillerRadioButton)
                    .addComponent(horrorCrimeRadioButton))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        horrorPanelLayout.setVerticalGroup(
            horrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(horrorPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(horroThrillerRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(horrorCrimeRadioButton)
                .addGap(26, 26, 26))
        );

        getContentPane().add(horrorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(667, 181, -1, 132));

        romancePanel.setBackground(new java.awt.Color(255, 153, 255));
        romancePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        romanceSubButtonGroup.add(romanceDramaRadioButton);
        romanceDramaRadioButton.setText("Drama");
        romancePanel.add(romanceDramaRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 17, -1, -1));

        romanceSubButtonGroup.add(romanceComedyRadioButton);
        romanceComedyRadioButton.setText("Comedy Drama");
        romancePanel.add(romanceComedyRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 93, -1, -1));

        getContentPane().add(romancePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 181, -1, 132));

        actionPanel.setBackground(new java.awt.Color(241, 15, 15));

        actionSubButtonGroup.add(actionThrillerRadioButton);
        actionThrillerRadioButton.setText("Thriller");

        actionSubButtonGroup.add(actionSuperheroRadioButton);
        actionSuperheroRadioButton.setText("Superhero");

        javax.swing.GroupLayout actionPanelLayout = new javax.swing.GroupLayout(actionPanel);
        actionPanel.setLayout(actionPanelLayout);
        actionPanelLayout.setHorizontalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actionThrillerRadioButton)
                    .addComponent(actionSuperheroRadioButton))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        actionPanelLayout.setVerticalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(actionThrillerRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(actionSuperheroRadioButton)
                .addGap(17, 17, 17))
        );

        getContentPane().add(actionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 181, -1, -1));

        setSize(new java.awt.Dimension(809, 363));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dramaComedyRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dramaComedyRadioButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_dramaComedyRadioButtonActionPerformed

    private void actionRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionRadioButtonActionPerformed
        // TODO add your handling code here:
         actionRadioButton.setSelected(true);
        romanceRadioButton.setSelected(false);
        fantasyRadioButton.setSelected(false);
        dramaRadioButton.setSelected(false);
        comedyRadioButton.setSelected(false);
        horrorRadioButton.setSelected(false);
        
    }//GEN-LAST:event_actionRadioButtonActionPerformed

    private void romanceRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_romanceRadioButtonActionPerformed
        // TODO add your handling code here:
         actionRadioButton.setSelected(false);
        romanceRadioButton.setSelected(true);
        fantasyRadioButton.setSelected(false);
        dramaRadioButton.setSelected(false);
        comedyRadioButton.setSelected(false);
        horrorRadioButton.setSelected(false);
        
    }//GEN-LAST:event_romanceRadioButtonActionPerformed

    private void fantasyRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fantasyRadioButtonActionPerformed
        // TODO add your handling code here:
         actionRadioButton.setSelected(false);
        romanceRadioButton.setSelected(false);
        fantasyRadioButton.setSelected(true);
        dramaRadioButton.setSelected(false);
        comedyRadioButton.setSelected(false);
        horrorRadioButton.setSelected(false);
    }//GEN-LAST:event_fantasyRadioButtonActionPerformed

    private void dramaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dramaRadioButtonActionPerformed
        // TODO add your handling code here:
        actionRadioButton.setSelected(false);
        romanceRadioButton.setSelected(false);
        fantasyRadioButton.setSelected(false);
        dramaRadioButton.setSelected(true);
        comedyRadioButton.setSelected(false);
        horrorRadioButton.setSelected(false);
    }//GEN-LAST:event_dramaRadioButtonActionPerformed

    private void comedyRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comedyRadioButtonActionPerformed
        // TODO add your handling code here:
         actionRadioButton.setSelected(false);
        romanceRadioButton.setSelected(false);
        fantasyRadioButton.setSelected(false);
        dramaRadioButton.setSelected(false);
        comedyRadioButton.setSelected(true);
        horrorRadioButton.setSelected(false);
    }//GEN-LAST:event_comedyRadioButtonActionPerformed

    private void horrorRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horrorRadioButtonActionPerformed
        // TODO add your handling code here:
         actionRadioButton.setSelected(false);
        romanceRadioButton.setSelected(false);
        fantasyRadioButton.setSelected(false);
        dramaRadioButton.setSelected(false);
        comedyRadioButton.setSelected(false);
        horrorRadioButton.setSelected(true);
        
    }//GEN-LAST:event_horrorRadioButtonActionPerformed

    private void goTosubGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goTosubGenreActionPerformed
        // TODO add your handling code here:
        if(actionRadioButton.isSelected())
        {
            actionPanel.setVisible(true);
            romancePanel.setVisible(false);
            fantasyPanel.setVisible(false);
            dramaPanel.setVisible(false);
            comedyPanel.setVisible(false);
            horrorPanel.setVisible(false);
        }
         if(romanceRadioButton.isSelected())
        {
            romancePanel.setVisible(true);
            actionPanel.setVisible(false);
            comedyPanel.setVisible(false);
            dramaPanel.setVisible(false);
            fantasyPanel.setVisible(false);
            horrorPanel.setVisible(false);
        }
          if(fantasyRadioButton.isSelected())
        {
            fantasyPanel.setVisible(true);
            romancePanel.setVisible(false);
            dramaPanel.setVisible(false);
            horrorPanel.setVisible(false);
            comedyPanel.setVisible(false);
            actionPanel.setVisible(false);
        }
           if(dramaRadioButton.isSelected())
        {
            dramaPanel.setVisible(true);
            actionPanel.setVisible(false);
            fantasyPanel.setVisible(false);
            comedyPanel.setVisible(false);
            romancePanel.setVisible(false);
            horrorPanel.setVisible(false);
        }
            if(comedyRadioButton.isSelected())
        {
            comedyPanel.setVisible(true);
            actionPanel.setVisible(false);
            dramaPanel.setVisible(false);
            fantasyPanel.setVisible(false);
            romancePanel.setVisible(false);
            horrorPanel.setVisible(false);
        }
             if(horrorRadioButton.isSelected())
        {
            horrorPanel.setVisible(true);
            actionPanel.setVisible(false);
            romancePanel.setVisible(false);
            fantasyPanel.setVisible(false);
            dramaPanel.setVisible(false);
            comedyPanel.setVisible(false);
            
        }
        
    }//GEN-LAST:event_goTosubGenreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieSuggetions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieSuggetions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieSuggetions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieSuggetions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieSuggetions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JRadioButton actionRadioButton;
    private javax.swing.ButtonGroup actionSubButtonGroup;
    private javax.swing.JRadioButton actionSuperheroRadioButton;
    private javax.swing.JRadioButton actionThrillerRadioButton;
    private javax.swing.JRadioButton comedyActionRadioButton;
    private javax.swing.JRadioButton comedyComedyDramaRadioButton;
    private javax.swing.JRadioButton comedyDramaRadioButton;
    private javax.swing.JPanel comedyPanel;
    private javax.swing.JRadioButton comedyRadioButton;
    private javax.swing.JRadioButton comedyRomanceRadioButton;
    private javax.swing.ButtonGroup comedySubButtonGroup;
    private javax.swing.JRadioButton dramaComedyRadioButton;
    private javax.swing.JRadioButton dramaCrimeRadioButton;
    private javax.swing.JRadioButton dramaFictionRadioButton;
    private javax.swing.JPanel dramaPanel;
    private javax.swing.JRadioButton dramaRadioButton;
    private javax.swing.ButtonGroup dramaSubButtonGroup;
    private javax.swing.JRadioButton dramaThrillerRadioButton;
    private javax.swing.JRadioButton fantasyActionRadioButton;
    private javax.swing.JRadioButton fantasyAdventureRadioButton;
    private javax.swing.JRadioButton fantasyDramaRadioButton;
    private javax.swing.JPanel fantasyPanel;
    private javax.swing.JRadioButton fantasyRadioButton;
    private javax.swing.ButtonGroup fantasySubButtonGroup;
    private javax.swing.ButtonGroup genreButton;
    private javax.swing.JLabel genreLabel;
    private javax.swing.JPanel genrepanel;
    private javax.swing.JButton goTosubGenre;
    private javax.swing.JRadioButton horroThrillerRadioButton;
    private javax.swing.JRadioButton horrorCrimeRadioButton;
    private javax.swing.JPanel horrorPanel;
    private javax.swing.JRadioButton horrorRadioButton;
    private javax.swing.ButtonGroup horrorSubButtonGroup;
    private javax.swing.JRadioButton romanceComedyRadioButton;
    private javax.swing.JRadioButton romanceDramaRadioButton;
    private javax.swing.JPanel romancePanel;
    private javax.swing.JRadioButton romanceRadioButton;
    private javax.swing.ButtonGroup romanceSubButtonGroup;
    // End of variables declaration//GEN-END:variables
}
