/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movieknight;

//import java.io.File;
import java.io.*;

/**
 *
 * @author User
 */
public class SignupPage extends javax.swing.JFrame {

    /**
     * Creates new form SignupPage
     */
    public SignupPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        regPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        maleRadiobutton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        otherRadioButton = new javax.swing.JRadioButton();
        useridTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        passwordTextField = new javax.swing.JTextField();
        Backbutton = new javax.swing.JButton();
        ageTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jCheckBox2.setText("jCheckBox2");

        jCheckBox1.setText("jCheckBox1");

        jButton1.setText("Submit");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        regPanel.setBackground(new java.awt.Color(255, 255, 255));
        regPanel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Name");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        regPanel.add(jLabel1);
        jLabel1.setBounds(146, 21, 80, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Age");
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        regPanel.add(jLabel2);
        jLabel2.setBounds(146, 89, 90, 38);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Gender");
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        regPanel.add(jLabel3);
        jLabel3.setBounds(150, 160, 90, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("User ID");
        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        regPanel.add(jLabel4);
        jLabel4.setBounds(150, 240, 100, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Password");
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        regPanel.add(jLabel5);
        jLabel5.setBounds(146, 321, 110, 40);

        nameTextField.setText(" ");
        regPanel.add(nameTextField);
        nameTextField.setBounds(300, 20, 163, 40);

        buttonGroup1.add(maleRadiobutton);
        maleRadiobutton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        maleRadiobutton.setText("Male");
        regPanel.add(maleRadiobutton);
        maleRadiobutton.setBounds(296, 166, 82, 33);

        buttonGroup1.add(femaleRadioButton);
        femaleRadioButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        femaleRadioButton.setText("Female");
        regPanel.add(femaleRadioButton);
        femaleRadioButton.setBounds(396, 166, 93, 33);

        buttonGroup1.add(otherRadioButton);
        otherRadioButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        otherRadioButton.setText("Other");
        regPanel.add(otherRadioButton);
        otherRadioButton.setBounds(515, 166, 82, 33);

        useridTextField.setText("   ");
        regPanel.add(useridTextField);
        useridTextField.setBounds(296, 243, 170, 40);

        jButton2.setBackground(new java.awt.Color(0, 51, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Submit");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        regPanel.add(jButton2);
        jButton2.setBounds(140, 390, 150, 40);
        regPanel.add(passwordTextField);
        passwordTextField.setBounds(300, 320, 170, 40);

        Backbutton.setBackground(new java.awt.Color(0, 0, 0));
        Backbutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Backbutton.setForeground(new java.awt.Color(255, 255, 255));
        Backbutton.setText("Back");
        Backbutton.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbuttonActionPerformed(evt);
            }
        });
        regPanel.add(Backbutton);
        Backbutton.setBounds(460, 470, 150, 40);
        regPanel.add(ageTextField);
        ageTextField.setBounds(300, 90, 160, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\2.1\\MovieKnight\\MovieKnight\\src\\movieknight\\images.jpg")); // NOI18N
        regPanel.add(jLabel6);
        jLabel6.setBounds(0, 0, 640, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(regPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(regPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        setSize(new java.awt.Dimension(656, 580));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Profile ob1 = new Profile();

        ob1.setName(nameTextField.getText());
        int gotAge = Integer.parseInt(ageTextField.getText());
        ob1.setAge(gotAge);

        if (maleRadiobutton.isSelected()) {
            //ob1.setGender(maleRadiobutton.get);
            ob1.setGender("Male");
        } else if (femaleRadioButton.isSelected()) {
            ob1.setGender("Female");
        } else if (otherRadioButton.isSelected()) {
            ob1.setGender("Other");
        }

        ob1.setUserID(useridTextField.getText());
        ob1.setPassword(passwordTextField.getText());

        String fileToOpen = "E:\\MovieKnight\\Proflie Database\\" + ob1.getUserID() + ".txt";
        File newProfileFile = new File(fileToOpen);

        try {
            FileOutputStream f = new FileOutputStream(new File(fileToOpen));
            ObjectOutputStream o = new ObjectOutputStream(f);

            // Write objects to file
            o.writeObject(ob1);
            //o.writeObject(p2);

            o.close();
            f.close();

        } catch (FileNotFoundException e) {
            System.out.println("File not found");
        } catch (IOException e) {
            System.out.println("Error initializing stream");
        }

        new TwoChoices().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbuttonActionPerformed
        // TODO add your handling code here:
        new Welcome().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbutton;
    private javax.swing.JTextField ageTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JRadioButton maleRadiobutton;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JRadioButton otherRadioButton;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JPanel regPanel;
    private javax.swing.JTextField useridTextField;
    // End of variables declaration//GEN-END:variables
}
