/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movieknight;

/**
 *
 * @author User
 */
public class TwoChoices extends javax.swing.JFrame {

    /**
     * Creates new form TwoChoices
     */
    public TwoChoices() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenu1 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        panelTwoChoices = new javax.swing.JPanel();
        movieofChoice = new javax.swing.JRadioButton();
        movieSuggestion = new javax.swing.JRadioButton();
        nextInTwoChoices = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel2.setText("Or do you want suggestions?");

        jLabel1.setText("Is there a movie you want to watch?");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panelTwoChoices.setBackground(new java.awt.Color(204, 204, 255));
        panelTwoChoices.setPreferredSize(new java.awt.Dimension(705, 622));
        panelTwoChoices.setLayout(null);

        movieofChoice.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(movieofChoice);
        movieofChoice.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        movieofChoice.setForeground(new java.awt.Color(255, 255, 255));
        movieofChoice.setText("Movie of Choice");
        movieofChoice.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelTwoChoices.add(movieofChoice);
        movieofChoice.setBounds(70, 140, 240, 40);

        movieSuggestion.setBackground(new java.awt.Color(204, 0, 51));
        buttonGroup1.add(movieSuggestion);
        movieSuggestion.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        movieSuggestion.setForeground(new java.awt.Color(255, 255, 255));
        movieSuggestion.setText("Movie Suggestion");
        movieSuggestion.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        movieSuggestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieSuggestionActionPerformed(evt);
            }
        });
        panelTwoChoices.add(movieSuggestion);
        movieSuggestion.setBounds(80, 360, 300, 50);

        nextInTwoChoices.setBackground(new java.awt.Color(0, 0, 0));
        nextInTwoChoices.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        nextInTwoChoices.setForeground(new java.awt.Color(255, 255, 255));
        nextInTwoChoices.setText("NEXT");
        nextInTwoChoices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextInTwoChoicesActionPerformed(evt);
            }
        });
        panelTwoChoices.add(nextInTwoChoices);
        nextInTwoChoices.setBounds(80, 450, 89, 39);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Choose One Option TO Go");
        panelTwoChoices.add(jLabel3);
        jLabel3.setBounds(60, 0, 550, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\2.1\\MovieKnight\\MovieKnight\\src\\movieknight\\217860483d2ca4970f728dc765c9d18e.jpg")); // NOI18N
        panelTwoChoices.add(jLabel4);
        jLabel4.setBounds(0, 0, 680, 550);

        getContentPane().add(panelTwoChoices);
        panelTwoChoices.setBounds(3, 1, 690, 610);

        setSize(new java.awt.Dimension(702, 607));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nextInTwoChoicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextInTwoChoicesActionPerformed
        // TODO add your handling code here:
        if (movieSuggestion.isSelected()) {
            new MovieSuggetions().setVisible(true);
            this.setVisible(false);
        }

    }//GEN-LAST:event_nextInTwoChoicesActionPerformed

    private void movieSuggestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieSuggestionActionPerformed
        // TODO add your handling code here:
        movieSuggestion.setSelected(true);
        movieofChoice.setSelected(false);
    }//GEN-LAST:event_movieSuggestionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TwoChoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TwoChoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TwoChoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TwoChoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TwoChoices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JRadioButton movieSuggestion;
    private javax.swing.JRadioButton movieofChoice;
    private javax.swing.JButton nextInTwoChoices;
    private javax.swing.JPanel panelTwoChoices;
    // End of variables declaration//GEN-END:variables
}
