/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movieknight;

/**
 *
 * @author User
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    //logInPanel.setVisible(false);
    public int flag=0;
    public Welcome() {
        initComponents();
        //logInPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        welcomePanel = new javax.swing.JPanel();
        welcomelabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        SignInButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ContinueasGuestButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        LogInButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        welcomePanel.setBackground(new java.awt.Color(153, 153, 255));
        welcomePanel.setPreferredSize(new java.awt.Dimension(680, 600));
        welcomePanel.setLayout(null);

        welcomelabel.setBackground(new java.awt.Color(255, 255, 255));
        welcomelabel.setFont(new java.awt.Font("Vivaldi", 3, 36)); // NOI18N
        welcomelabel.setForeground(new java.awt.Color(204, 255, 255));
        welcomelabel.setText("Welcome to Movie Knight ");
        welcomePanel.add(welcomelabel);
        welcomelabel.setBounds(120, 10, 411, 145);

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Yu Gothic", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Willing to open an account?");
        welcomePanel.add(jLabel1);
        jLabel1.setBounds(83, 171, 281, 30);

        SignInButton.setBackground(new java.awt.Color(0, 0, 0));
        SignInButton.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        SignInButton.setForeground(new java.awt.Color(255, 255, 255));
        SignInButton.setText("Sign up");
        SignInButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SignInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInButtonActionPerformed(evt);
            }
        });
        welcomePanel.add(SignInButton);
        SignInButton.setBounds(368, 177, 99, 21);

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Continue as guest?");
        welcomePanel.add(jLabel2);
        jLabel2.setBounds(130, 220, 182, 30);

        ContinueasGuestButton.setBackground(new java.awt.Color(0, 0, 0));
        ContinueasGuestButton.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        ContinueasGuestButton.setForeground(new java.awt.Color(255, 255, 255));
        ContinueasGuestButton.setText("Next>>");
        ContinueasGuestButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ContinueasGuestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueasGuestButtonActionPerformed(evt);
            }
        });
        welcomePanel.add(ContinueasGuestButton);
        ContinueasGuestButton.setBounds(368, 219, 99, 21);

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Have an Account?");
        welcomePanel.add(jLabel3);
        jLabel3.setBounds(140, 270, 170, 30);

        LogInButton.setBackground(new java.awt.Color(0, 0, 0));
        LogInButton.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        LogInButton.setForeground(new java.awt.Color(255, 255, 255));
        LogInButton.setText("Log in");
        LogInButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LogInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInButtonActionPerformed(evt);
            }
        });
        welcomePanel.add(LogInButton);
        LogInButton.setBounds(368, 273, 99, 21);

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\2.1\\MovieKnight\\MovieKnight\\src\\movieknight\\godzillabackground1.jpg")); // NOI18N
        welcomePanel.add(jLabel4);
        jLabel4.setBounds(-10, 0, 630, 320);

        getContentPane().add(welcomePanel);
        welcomePanel.setBounds(0, 0, 620, 320);

        setSize(new java.awt.Dimension(638, 377));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SignInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInButtonActionPerformed
        // TODO add your handling code here:
        new SignupPage().setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_SignInButtonActionPerformed

    private void ContinueasGuestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueasGuestButtonActionPerformed
        // TODO add your handling code here:
        new TwoChoices().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ContinueasGuestButtonActionPerformed

    private void LogInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInButtonActionPerformed
        // TODO add your handling code here:
        //logInPanel.setVisible(true);
        new LogInPage().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_LogInButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ContinueasGuestButton;
    private javax.swing.JButton LogInButton;
    private javax.swing.JButton SignInButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel welcomePanel;
    private javax.swing.JLabel welcomelabel;
    // End of variables declaration//GEN-END:variables
}
